- alias: Stop Chromecast on Activity change
  trigger:
    - platform: state
      entity_id: sensor.living_room_entertainment
      from: "Chromecast Audio"
  action:
    - service: media_player.media_stop
      data:
        entity_id: media_player.living_room

- alias: Stop Chromecast on Activity change
  trigger:
    - platform: state
      entity_id: sensor.living_room_entertainment
      from: "Watch Chromecast"
  action:
    - service: media_player.media_stop
      data:
        entity_id: media_player.living_room
