############################################################
#
# Home Assistant Door Alarm Automation 
#
############################################################

- alias: "NOTIFY All when Back Door is OPENED and NOT HOME" 
  trigger:
    - platform: state
      entity_id: sensor.template_back_door
      to: 'open'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: 'group.all_mobile_devices'
        state: 'not_home'
      - condition: state
        entity_id: 'input_boolean.night_mode'
        state: 'on'
  action:
    - service: notify.ios_all
      data_template:
        message: 'ALARM: Back Door Opened'

- alias: "NOTIFY All when Front Door is OPENED and NOT HOME" 
  trigger:
    - platform: state
      entity_id: sensor.template_front_door
      to: 'open'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: 'group.all_mobile_devices'
        state: 'not_home'
      - condition: state
        entity_id: 'input_boolean.night_mode'
        state: 'on'
  action:
    - service: notify.ios_all
      data_template:
        message: 'ALARM: Front Door Opened'

- alias: "NOTIFY All when Summer House Door is OPENED and NOT HOME" 
  trigger:
    - platform: state
      entity_id: sensor.template_summer_house_door 
      to: 'open'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: 'group.all_mobile_devices'
        state: 'not_home'
      - condition: state
        entity_id: 'input_boolean.night_mode'
        state: 'on'
  action:
    - service: notify.ios_all
      data_template:
        message: 'ALARM: Summer House Door Opened'

- alias: "NOTIFY All when Utility Room Door is OPENED and NOT HOME" 
  trigger:
    - platform: state 
      entity_id: sensor.template_utility_room_door
      to: 'open'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: 'group.all_mobile_devices'
        state: 'not_home'
      - condition: state
        entity_id: 'input_boolean.night_mode'
        state: 'on'
  action:
    - service: notify.ios_all
      data_template:
        message: 'ALARM: Utility Room Door Opened'

- alias: "NOTIFY All when Workshop is OPENED and NOT HOME" 
  trigger:
    - platform: state
      entity_id: sensor.template_workshop_door
      to: 'open'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: 'group.all_mobile_devices'
        state: 'not_home'
      - condition: state
        entity_id: 'input_boolean.night_mode'
        state: 'on'
  action:
    - service: notify.ios_all
      data_template:
        message: 'ALARM: Workshop Door Opened'
