############################################################
#
# Home Assistant Front Lights PIR Automation 
#
############################################################

- alias: "Turn ON Front Lights when PIR channel is ACTIVATED"
  trigger:
    platform: mqtt
    topic: "house/controller/1" 
    payload: '4'
  condition:
    condition: state
    entity_id: 'sensor.light_sensor'
    state: 'Night'
  action:
    service: homeassistant.turn_on
    entity_id: script.front_floodlights_motion_timer

############################################################
#
# Home Assistant Front Lights Door Automation 
#
############################################################

- alias: "Turn ON Front Lights when Front Door is OPENED" 
  trigger:
    platform: state
    entity_id: binary_sensor.frontdoorswitch_sensor
    to: 'on'
  condition:
    condition: state
    entity_id: 'sensor.light_sensor'
    state: 'Night'
  action:
    service: homeassistant.turn_on
    entity_id: script.front_floodlights_motion_timer

############################################################
#
# Home Assistant Courtyard Lights when someone arrives HOME
#
############################################################

- alias: Turn ON front lights when zone is entered
  trigger:
    - platform: zone
      entity_id: device_tracker.graemes_iphone
      zone: zone.home
      event: enter
    - platform: zone
      entity_id: device_tracker.aileens_iphone
      zone: zone.home
      event: enter
  condition:
    condition: state
    entity_id: 'sensor.light_sensor'
    state: 'Night'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: script.front_floodlights_motion_timer
