############################################################
#
# START Night Mode On SCRIPT when Night Mode is ON
#
############################################################

- alias: START Night Mode On SCRIPT when Night Mode is ON
  trigger:
    platform: state
    entity_id: input_boolean.night_mode 
    to: 'on'
  action:
    service: script.turn_on
    entity_id: 
      - script.night_mode_on

############################################################
#
# START Night Mode Off SCRIPT when Night Mode is Off
#
############################################################

- alias: START Night Mode Off SCRIPT when Night Mode is OFF
  trigger:
    platform: state
    entity_id: input_boolean.night_mode 
    to: 'off'
  action:
    service: script.turn_on
    entity_id: 
      - script.night_mode_off
