############################################################
#
# Cinema Mode Plex Automations
#
############################################################

- alias: "Media Player Stopped"
  trigger:
    - platform: state
      entity_id: media_player.plex_for_lg_webos_043065
      to: 'idle'
  condition:
    condition: and 
    conditions:
      - condition: state
        entity_id: input_boolean.cinema_mode
        state: 'on'
      - condition: state
        entity_id: sensor.light_sensor
        state: 'Night'
  action:
    - service: scene.turn_on
      entity_id: scene.relax

- alias: "Media Player Paused"
  trigger:
    - platform: state
      entity_id: media_player.plex_for_lg_webos_043065
      from: 'playing'
      to: 'paused'
  condition:
    condition: and 
    conditions:
      - condition: state
        entity_id: input_boolean.cinema_mode
        state: 'on'
      - condition: state
        entity_id: sensor.light_sensor
        state: 'Night'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_low

- alias: "Media Player Playing"
  trigger:
    - platform: state
      entity_id: media_player.plex_for_lg_webos_043065
      to: 'playing'
  condition:
    condition: and 
    conditions:
      - condition: state
        entity_id: input_boolean.cinema_mode
        state: 'on'
      - condition: state
        entity_id: sensor.light_sensor
        state: 'Night'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_very_low
