############################################################
#
# ZWave Device Battery states
#
############################################################

- platform: template
  sensors:
    bathroom_motion_sensor_battery:
      value_template: '{{ states.zwave.bathroommotionsensor.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: zwave.bathroommotionsensor
      friendly_name: "Bathroom"

- platform: template
  sensors:
    kitchen_motion_sensor_battery:
      value_template: '{{ states.zwave.kitchenmotionsensor.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: zwave.kitchenmotionsensor
      friendly_name: "Kitchen"

- platform: template
  sensors:
    hall_motion_sensor_battery:
      value_template: '{{ states.zwave.hallmotionsensor.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: zwave.hallmotionsensor
      friendly_name: "Hall"

- platform: template
  sensors:
    porch_motion_sensor_battery:
      value_template: '{{ states.zwave.porchmotionsensor.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: zwave.porchmotionsensor
      friendly_name: "Porch"

- platform: template
  sensors:
    lowerstairs_motion_sensor_battery:
      value_template: '{{ states.zwave.mainstairslower.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: zwave.mainstairslower
      friendly_name: "Lower Stairs"

- platform: template
  sensors:
    upperstairs_motion_sensor_battery:
      value_template: '{{ states.zwave.mainstairsupper.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: zwave.mainstairsupper
      friendly_name: "Upper Stairs"

- platform: template
  sensors:
    summerhousedoor_sensor_battery:
      value_template: '{{ states.zwave.summerhousedoor.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: zwave.summerhousedoor
      friendly_name: "Summer House Door"

- platform: template
  sensors:
    backdoor_sensor_battery:
      value_template: '{{ states.zwave.backdoorswitch.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: zwave.backdoorswitch
      friendly_name: "Back Door"

- platform: template
  sensors:
    frontdoor_sensor_battery:
      value_template: '{{ states.zwave.frontdoorswitch.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: zwave.frontdoorswitch
      friendly_name: "Front Door"

- platform: template
  sensors:
    utilityroomdoor_sensor_battery:
      value_template: '{{ states.zwave.utilityroomswitch.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: zwave.utilityroomswitch
      friendly_name: "Utility Room Door"

- platform: template
  sensors:
    workshop_sensor_battery:
      value_template: '{{ states.zwave.workshopswitch.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: zwave.workshopswitch
      friendly_name: "Workshop Door"

- platform: template
  sensors:
    light_sensor_battery:
      value_template: '{{ states.zwave.lightsensor.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: zwave.lightsensor
      friendly_name: "Light Sensor"
