############################################################
#
# HP Server Integrated Lights Out Monitoring 
#
############################################################

- platform: hp_ilo
  name: Server
  host: !secret hp_ilo_server
  port: 443
  username: !secret hp_ilo_username
  password: !secret hp_ilo_password
  monitored_variables:
    - name: 'CPU Fan Speed'
      sensor_type: server_health
      unit_of_measurement: '%'
      value_template: '{{ ilo_data.fans["Fan 1"].speed[0] }}'
    - name: Inlet
      sensor_type: server_health
      unit_of_measurement: '°C'
      value_template: '{{ ilo_data.temperature["01-Inlet Ambient"].currentreading[0] }}'
    - name: Exhaust
      sensor_type: server_health
      unit_of_measurement: '°C'
      value_template: '{{ ilo_data.temperature["12-Sys Exhaust"].currentreading[0] }}'
    - name: Chipset
      sensor_type: server_health
      unit_of_measurement: '°C'
      value_template: '{{ ilo_data.temperature["05-Chipset"].currentreading[0] }}'
    - name: Memory
      sensor_type: server_health
      unit_of_measurement: '°C'
      value_template: '{{ ilo_data.temperature["03-P1 DIMM 1-2"].currentreading[0] }}'
    - name: Power Supply 
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["power_supplies"].status }}'
    - name: Processor
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["processor"].status }}'
    - name: Memory
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["memory"].status }}'
    - name: Temperature
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["temperature"].status }}'
    - name: Fans 
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["fans"].status }}'
    - name: Bios 
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["bios_hardware"].status }}'
    - name: Network
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["network"].status }}'
    - name: Server Health
      sensor_type: server_health


- platform: hp_ilo
  name: MediaServer
  host: !secret hp_ilo_mediaserver
  port: 443
  username: !secret hp_ilo_username
  password: !secret hp_ilo_password
  monitored_variables:
    - name: 'CPU Fan Speed'
      sensor_type: server_health
      unit_of_measurement: '%'
      value_template: '{{ ilo_data.fans["Fan 1"].speed[0] }}'
    - name: Inlet
      sensor_type: server_health
      unit_of_measurement: '°C'
      value_template: '{{ ilo_data.temperature["01-Inlet Ambient"].currentreading[0] }}'
    - name: Exhaust
      sensor_type: server_health
      unit_of_measurement: '°C'
      value_template: '{{ ilo_data.temperature["12-Sys Exhaust"].currentreading[0] }}'
    - name: Chipset
      sensor_type: server_health
      unit_of_measurement: '°C'
      value_template: '{{ ilo_data.temperature["05-Chipset"].currentreading[0] }}'
    - name: Memory
      sensor_type: server_health
      unit_of_measurement: '°C'
      value_template: '{{ ilo_data.temperature["03-P1 DIMM 1-2"].currentreading[0] }}'
    - name: Power Supply 
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["power_supplies"].status }}'
    - name: Processor
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["processor"].status }}'
    - name: Memory
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["memory"].status }}'
    - name: Temperature
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["temperature"].status }}'
    - name: Fans 
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["fans"].status }}'
    - name: Bios 
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["bios_hardware"].status }}'
    - name: Network
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["network"].status }}'
    - name: Server Health
      sensor_type: server_health

