############################################################
#
# Min/Max Sensor
#
############################################################
- platform: min_max 
  entity_ids: 
    - sensor.porchmotionsensor_temperature 
    - sensor.hallmotionsensor_temperature
    - sensor.kitchenmotionsensor_temperature
    - sensor.mainstairslower_temperature
    - sensor.mainstairsupper_temperature
    - sensor.bedroom_temperature
    - sensor.dining_room_thermostat_temperature
    - sensor.attic_temperature
  name: 'House_Minimum_Temperature'
  type: min

- platform: min_max 
  entity_ids: 
    - sensor.porchmotionsensor_temperature 
    - sensor.hallmotionsensor_temperature
    - sensor.kitchenmotionsensor_temperature
    - sensor.mainstairslower_temperature
    - sensor.mainstairsupper_temperature
    - sensor.bedroom_temperature
    - sensor.dining_room_thermostat_temperature
    - sensor.attic_temperature
  name: 'House_Maximum_Temperature'
  type: max

- platform: min_max 
  entity_ids: 
    - sensor.porchmotionsensor_temperature 
    - sensor.hallmotionsensor_temperature
    - sensor.kitchenmotionsensor_temperature
    - sensor.mainstairslower_temperature
    - sensor.mainstairsupper_temperature
    - sensor.bedroom_temperature
    - sensor.dining_room_thermostat_temperature
    - sensor.attic_temperature
  name: 'House_Mean_Temperature'
  type: mean

