############################################################
#
# Home Assistant Binary Sensors
#
############################################################


############################################################
#
# Aurora
#
############################################################

- platform: aurora


############################################################
#
# Workday
#
############################################################

- platform: workday
  country: UK
  excludes: holiday

############################################################
#
# ISS 
#
############################################################

#- platform: iss
#  show_on_map: true

############################################################
#
# Trend Sensors
#
############################################################

- platform: trend
  sensors:
    house_temp_trend:
      entity_id: sensor.house_temperature_mean
      friendly_name: 'Temperature Rising'
      device_class: heat

    house_temp_trend_invert:
      entity_id: sensor.house_temperature_mean
      friendly_name: 'Temperature Falling'
      device_class: heat
      invert: True

    power_trend:
      entity_id: sensor.energy_monitor 
      friendly_name: 'Demand Increasing'
      device_class: cold

    power_trend_invert:
      entity_id: sensor.energy_monitor 
      friendly_name: 'Demand Falling'
      device_class: cold
      invert: True

############################################################
#
# Water Tank 
#
############################################################

- platform: mqtt
  state_topic: "lorawan/gateway/1/5"
  name: "Charging"
  qos: 0
  payload_on: "1"
  payload_off: "0"

- platform: mqtt
  state_topic: "lorawan/gateway/1/6"
  name: "Fully Charged"
  qos: 0
  payload_on: "1"
  payload_off: "0"


