############################################################
#
# Home Assistant Camera Configuration
#
############################################################

#- platform: mjpeg
#  mjpeg_url: !secret camera1_url
#  name: Attic
#
#
- platform: ffmpeg
  input: !secret camera1_url
  name: CCTV Front
  extra_arguments: '-rtsp_transport udp -an -pred 1 -q:v 2'
#  extra_arguments: '-rtsp_transport tcp -preset ultrafast -vcodec libx264 -b 900k -tune zerolatency -an'

- platform: ffmpeg
  input: !secret camera2_url
  name: Attic
  extra_arguments: '-rtsp_transport udp -an -pred 1 -q:v 2'

#- platform: mjpeg
#  mjpeg_url: !secret camera1_url
#  name: Garden
#- platform: mjpeg 
#  mjpeg_url: !secret camera2_url
#  name: Courtyard
#
- platform: generic
  still_image_url: https://api.sat24.com/animated/GB/visual/3/GMT%20Standard%20Time/6849114
  name: Weather Map
