############################################################
#
# Home Assistant Media Players
#
############################################################

- platform: plex
- platform: samsungtv
  host: !secret samsungtv_host 
- platform: cast
