- platform: webostv
  host: !secret webostv_host
  name: !secret webostv_name

- platform: twilio_sms
  name: twilio_sms
  from_number: !secret twilio_from_number

- platform: smtp
  name: as_email
  server: !secret smtp_server
  port: !secret smtp_port
  sender: !secret smtp_sender
  recipient: !secret as_email

- platform: smtp
  name: gs_email
  server: !secret smtp_server
  port: !secret smtp_port
  sender: !secret smtp_sender
  recipient: !secret gs_email

- platform: html5
  name: HTML5
  gcm_api_key: !secret gcm_api_key
  gcm_sender_id: !secret gcm_sender_id

- platform: group
  name: as_sms
  services:
    - service: twilio_sms
      data:
        target: !secret aileen_twilio

- platform: group
  name: gs_sms
  services:
    - service: twilio_sms
      data:
        target: !secret graeme_twilio
  
- platform: group
  name: notify_aileen
  services:
    - service: as_sms
    - service: as_email
    - service: ios_aileens_iphone

- platform: group
  name: notify_graeme 
  services:
    - service: gs_sms
    - service: gs_email
    - service: ios_graemes_iphone

- platform: group
  name: ios_all
  services:
    - service: ios_aileens_iphone
    - service: ios_graemes_iphone

- platform: group
  name: notify_all_email
  services:
    - service: gs_email
    - service: as_email

- platform: group
  name: notify_water
  services:
    - service: notify_aileen
    - service: notify_graeme
    - service: html5
    - service: rasplex

- platform: group
  name: notify_all
  services:
    - service: notify_aileen
    - service: notify_graeme
    - service: html5
    - service: rasplex

- platform: ios
