homeassistant:
  customize:
    sensor.living_room_nest_protect_battery_health:
      icon: mdi:battery
    sensor.living_room_nest_protect_co_status:
      icon: mdi:nest-protect
    sensor.living_room_nest_protect_smoke_status:
      icon: mdi:nest-protect
    binary_sensor.living_room_nest_protect_online:
      friendly_name: "Living Rooom"
      icon: mdi:nest-protect

    sensor.upstairs_nest_protect_battery_health:
      icon: mdi:battery
    sensor.upstairs_nest_protect_co_status:
      icon: mdi:nest-protect
    sensor.upstairs_nest_protect_smoke_status:
      icon: mdi:nest-protect
    binary_sensor.upstairs_nest_protect_online:
      friendly_name: "Upstairs"
      icon: mdi:nest-protect

group:
  protects:
    name: Nest Protects
    entities:
      - binary_sensor.living_room_nest_protect_online
      - binary_sensor.upstairs_nest_protect_online

automation:
  - alias: Nest Protect Emergency
    hide_entity: true
    trigger:
      platform: state
      entity_id:
        - sensor.living_room_nest_protect_smoke_status
        - sensor.living_room_nest_protect_co_status
        - sensor.upstairs_nest_protect_smoke_status
        - sensor.upstairs_nest_protect_co_status
      to: 'Emergency'
    action:
      - service: light.turn_on
        entity_id:
          - group.all_lights
        data:
          flash: long
          color: white
          brightness: 255
      - service: light.turn_on
        entity_id:
          - group.all_lights
      - service: notify.notify_all
        data_template:
          title: 'Emergency'
          message: "An emergency has been detected on {{ trigger.to_state.attributes.friendly_name }} Please investigate IMMEDIATELY."
      - service: tts.amazon_polly_say
        data_template:
          entity_id: media_player.living_room_audio
          message: "An emergency has been detected on {{ trigger.to_state.attributes.friendly_name }} Please investigate IMMEDIATELY."

  - alias: Notify if Nest Protect is Offline
    hide_entity: true
    trigger:
      platform: state
      entity_id:
        - binary_sensor.living_room_nest_protect_online
        - binary_sensor.upstairs_nest_protect_online
      from: 'on'
    action:
      - service: notify.notify_all
        data_template:
          title: 'Emergency'
          message: "An emergency has been detected on {{ trigger.to_state.attributes.friendly_name }} Please investigate IMMEDIATELY."
      - service: tts.amazon_polly_say
        data_template:
          entity_id: media_player.living_room_audio
          message:  "The {{ trigger.to_state.attributes.friendly_name }} is now {{ (trigger.to_state.state)|replace('_', ' ') }}.  Please check immediately."
