################################################################
## Packages / Television
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'television'

    ################################################
    ## Script
    ################################################

    automation.turn_on_television:
      <<: *customize
      friendly_name: "Turn On Television"
      icon: mdi:television

    automation.turn_off_television:
      <<: *customize
      friendly_name: "Turn On Television"
      icon: mdi:television

    ################################################
    ## switch 
    ################################################

    switch.television:
      <<: *customize
      friendly_name: "Television"
      icon: mdi:television
      persistent: true

################################################
## Switch 
################################################

switch:
  platform: template
  switches:
    television:
      value_template: "{% if is_state('sensor.harmony', 'PowerOff') or is_state('sensor.harmony', 'None') %}off{% else %}on{% endif %}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_television 
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_television 
        
################################################
## Script 
################################################

script:
  turn_on_television:
    sequence:
      - service: remote.turn_on
        data_template:
          entity_id: remote.harmony
          activity: >
            24357585

  turn_off_television:
    sequence:
      - service: remote.turn_on
        data_template:
          entity_id: remote.harmony
          activity: >
            -1

